### ISSUE TITLE
unpoller.conf path for Docker

### ISSUE THREAD

**Issue by McMacaron** [unpoller/unpoller#364]
Hello David,

I have spent more than 20hours installing unpoller to Ubuntu 21.04 64bit. It seems that everything is working but Unpollen can not pick up settings from unpoller.conf file. Instead of that it is taking some default config file with URL https://127.0.0.1:8443: unifi controller. I have UDM Pro...

I have even try to set path with 
docker run -v /home/ubuntu/Docker/unpoller:/config/unpoller.conf golift/unifi-poller

Absolutely nothing works. 

It tried permissions to folders. Set config to different etc locations....

Last part of Yaml:
unpoller:
    container_name: Unpoller01
    restart: unless-stopped
    image: golift/unifi-poller:latest
    depends_on:
      - influxdb
      - grafana
    volumes:
      - /home/ubuntu/Docker/unpoller:/config

unpollen.conf:

# UniFi Poller v2 primary configuration file. TOML FORMAT #
###########################################################

[poller]

  debug = true

  quiet = false

  plugins = []

#### OUTPUTS

[prometheus]
  disable = true

  http_listen = "1.0.0.0:9130"

  ssl_cert_path = ""
  ssl_key_path  = ""

  report_errors = false

  dead_ports = false

[influxdb]
  disable = false

  url  = "http://192.168.88.138:8086"
  user = "unifipoller"

  pass = "xxx"

  db = "unifi"

  verify_ssl = false

  interval = "30s"
 
  dead_ports = false

[loki]
  url = ""

  user       = ""
  pass       = ""
  verify_ssl = false
  tenant_id  = ""
  interval   = "2m"
  timeout    = "10s"

[webserver]
  enable = false
  port   = 37288

  html_path     = "/usr/lib/unifi-poller/web"
  ssl_cert_path = ""
  ssl_key_path  = ""

  max_events = 200

[webserver.accounts]

#### INPUTS

[unifi]

  dynamic = false

[unifi.defaults]

  url = "https://192.168.88.1"

  user = "unifipoller"

  pass = "ssssss"

  sites = ["all"]

  save_sites = true

  hash_pii = false

  save_ids = true

  save_events = true

  save_alarms = false

  save_anomalies = true

  save_dpi = true

  save_rogue = true

  verify_ssl = false

  ssl_cert_paths = []

**Comment by davidnewhall** [comment]
Rename it to `unifi-poller.conf`. The documentation is currently ahead of the app. It was hastily renamed.

**Comment by McMacaron** [comment]
Uff Uff. Thanks that works instantly. I thought I will give up. It is running nicely on Raspberry Pi 4, ubuntu server 21.04 64bit. I had a problem with Raspbian 32bit as Influx ran one of the raspberry core on 100% and the second was jumping up and down from 40%-100%. Even the swap file is empty now and it is using just 470Mb of memory
Now one core is running on 5% with 471. So it is perfectly suitable for unpoller. I will make an easy install tutorial for it.

**Comment by Videothek** [comment]
Hello, 

i have the same problem.

I edited like 20 different versions of the .conf file.

I am using the config file down below, i changed all the variables.

When I run unpoller with this docker command: 

`$sudo docker run -v /your-local-location/unpoller.conf:/config/unpoller.conf golift/unifi-poller
`

I get this output:

`
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2021/07/19 20:13:01 [INFO] Loading Configuration File: /etc/unifi-poller/up.conf
2021/07/19 20:13:01 [INFO] UniFi Poller v2.1.3 Starting Up! PID: 1
2021/07/19 20:13:01 [ERROR] Controller 1 of 1 Auth or Connection Error, retrying: unifi controller: making request: Get "https://127.0.0.1:8443/": dial tcp 127.0.0.1:8443: connect: connection refused
2021/07/19 20:13:01 [INFO] Poller->InfluxDB started, interval: 30s, dp: false, db: unifi, url: http://127.0.0.1:8086
2021/07/19 20:13:01 [INFO] Internal web server disabled!
2021/07/19 20:13:01 [INFO] Loki config missing (or disabled), Loki output disabled!
2021/07/19 20:13:01 [INFO] Prometheus exported at http://0.0.0.0:9130/ - namespace: unifipoller
`


It is really weird that he uses my defined database but not the new ip addresses that i defined.

Does anyone have a clue what this could be?

Thanks in Advance :-).
 

Config example:

# UniFi Poller v2 primary configuration file. TOML FORMAT #
###########################################################

[poller]
  # Turns on line numbers, microsecond logging, and a per-device log.
  # The default is false, but I personally leave this on at home (four devices).
  # This may be noisy if you have a lot of devices. It adds one line per device.
  debug = false

  # Turns off per-interval logs. Only startup and error logs will be emitted.
  # Recommend enabling debug with this setting for better error logging.
  quiet = false

  # Load dynamic plugins. Advanced use; only sample mysql plugin provided by default.
  plugins = []

#### OUTPUTS

    # If you don't use an output, you can disable it.

[prometheus]
  disable = false
  # This controls on which ip and port /metrics is exported when mode is "prometheus".
  # This has no effect in other modes. Must contain a colon and port.
  http_listen = "0.0.0.0:9130"
  # Adding an SSL Cert and Cert Key will make Poller listen with SSL/https.
  ssl_cert_path = ""
  ssl_key_path  = ""
  # Errors are rare. Setting this to true will report them to Prometheus.
  report_errors = false
  ## Record data for disabled or down (unlinked) switch ports.
  dead_ports = false

[influxdb]
  disable = false
  # InfluxDB does not require auth by default, so the user/password are probably unimportant.
  url  = "http://127.0.0.1:8086"
  user = "unifipoller"
  # Password for InfluxDB user (above).
  # If the password provided here begins with file:// then the password is read in from
  # the file path that follows the file:// prefix. ex: file:///etc/influxdb/passwd.file
  pass = "unifipoller"
  # Be sure to create this database. See the InfluxDB Wiki page for more info.
  db = "unifi"
  # If your InfluxDB uses a valid SSL cert, set this to true.
  verify_ssl = false
  # The UniFi Controller only updates traffic stats about every 30 seconds.
  # Setting this to something lower may lead to "zeros" in your data.
  # If you're getting zeros now, set this to "1m"
  interval = "30s"
  ## Record data for disabled or down (unlinked) switch ports.
  dead_ports = false

# To enable output of UniFi Events to Loki, add a URL; it's disabled otherwise.
# User, pass and tenant_id are optional and most folks wont set them.
# Pick which logs you want per-controller in the [unifi.controller] section.
# This is a new feature. Feedback welcome!
[loki]
  url = ""
  # The rest of this is advanced & optional. See wiki.
  user       = ""
  pass       = ""
  verify_ssl = false
  tenant_id  = ""
  interval   = "2m"
  timeout    = "10s"

# Poller has an optional web server. To turn it on, set enable to true. If you
# wish to use SSL, provide SSL cert and key paths. This interface is currently
# read-only; it just displays information, like logs, devices and clients.
# Notice: Enabling the web server with many sites will increase memory usage.
# This is a new feature and lacks a UI, enabling only recommended for testing.
[webserver]
  enable = false
  port   = 37288
  # The HTML path is different on Windows and BSD/macOS.
  html_path     = "/usr/lib/unifi-poller/web"
  ssl_cert_path = ""
  ssl_key_path  = ""
  # How many events per event group to hold. 200-2000. Use fewer with many sites.
  # With 1 site, you'll have a max total of 9 event groups; 1 per plugin, 4 per site.
  # Each site adds 1 event group for each of these inputs that is enabled:
  #   save_ids, save_events, save_anomalies, save_alarms.
  max_events = 200

# By default the web interface does not require authentication. You can change
# that by adding a username and password hash (or multiple) below.
# To create a hash, run unifi-poller with the -e CLI argument. See Wiki for more!
[webserver.accounts]
# username = "password-hash"
# captain = "$2a$04$mxw6i0LKH6u46oaLK2cq5eCTAAFkfNiRpzNbz.EyvJZZWNa2FzIlS"

#### INPUTS

[unifi]
  # Setting this to true and providing default credentials allows you to skip
  # configuring controllers in this config file. Instead you configure them in
  # your prometheus.yml config. Prometheus then sends the controller URL to
  # unifi-poller when it performs the scrape. This is useful if you have many,
  # or changing controllers. See wiki for more.
  dynamic = false

# The following section contains the default credentials/configuration for any
# dynamic controller (see above section), or the primary controller if you do not
# provide one and dynamic is disabled. In other words, you can just add your
# controller here and delete the following section. The internal defaults are
# shown below. Any missing values will assume these displayed defaults.

[unifi.defaults]
  # URL for the UniFi Controller. Do not add any paths after the host:port.
  # Do not use port 8443 if you have a UDM; just use "https://ip".
  url = "https://127.0.0.1:8443"

  # Make a read-only user in the UniFi Admin Settings, allow it access to all sites.
  user = "unifipoller"

  # Password for UniFi controller user (above).
  # If the password provided here begins with file:// then the password is read in from
  # the file path that follows the file:// prefix. ex: file:///etc/unifi/password.file
  # ex: file:///etc/unifi/passwd.file, windows: file://C:\\UserData\\Unifi\\Passwd.txt
  pass = "unifipoller"

  # If the controller has more than one site, specify which sites to poll here.
  # Set this to ["default"] to poll only the first site on the controller.
  # A setting of ["all"] will poll all sites; this works if you only have 1 site too.
  sites = ["all"]

  # Enable collection of site data. This data powers the Network Sites dashboard.
  # It's not valuable to everyone and setting this to false will save resources.
  save_sites = true

  # Hash, with md5, client names and MAC addresses. This attempts to protect
  # personally identifiable information. Most users won't want to enable this.
  hash_pii = false

  # Enable collection of Intrusion Detection System Data (InfluxDB/Loki only).
  # Only useful if IDS or IPS are enabled on one of the sites. This may store
  # a lot of information. Only recommended for testing and debugging. There
  # may not be any dashboards to display this data. It can be used for annotations.
  # Enable this only if using InfluxDB or Loki. This will leak PII data!
  save_ids = false

  # Enable collection of UniFi Events (InfluxDB/Loki only).
  # This may store a lot of information. Only recommended for testing and debugging.
  # There are no dashboards to display this data. It can be used for annotations.
  # This is a new (June, 2020) feature. Please provide feedback if you try it out!
  # Enable this only if using InfluxDB or Loki. This will leak PII data!
  save_events = false

  # Enable collection of UniFi Alarms (InfluxDB/Loki only).
  # There are no dashboards to display this data. It can be used for annotations.
  # This is a new (June, 2020) feature. Please provide feedback if you try it out!
  # Enable this only if using InfluxDB or Loki. This will leak PII data!
  save_alarms = false

  # Enable collection of UniFi Anomalies (InfluxDB/Loki only).
  # There are no dashboards to display this data. It can be used for annotations.
  # This is a new (June, 2020) feature. Please provide feedback if you try it out!
  # Enable this only if using InfluxDB or Loki.
  save_anomalies = false

  # Enable collection of Deep Packet Inspection data. This data breaks down traffic
  # types for each client and site, it powers a dedicated DPI dashboard.
  # Enabling this adds roughly 150 data points per client.  That's 6000 metrics for
  # 40 clients.  This adds a little bit of poller run time per interval and causes
  # more API requests to your controller(s). Don't let these "cons" sway you:
  # it's cool data. Please provide feedback on your experience with this feature.
  save_dpi = false

  ## Enabling save_rogue stores even more data in your time series databases.
  ## This saves neighboring access point metrics in a dedicated table or namespace.
  save_rogue = false

  # If your UniFi controller has a valid SSL certificate (like lets encrypt),
  # you can enable this option to validate it. Otherwise, any SSL certificate is
  # valid. If you don't know if you have a valid SSL cert, then you don't have one.
  verify_ssl = false

  ## You may provide a list of SSL cert files (PEM format) that you expect your
  ## controller to use. As long as one of the certs you provide here shows up in
  ## the cert trust chain the controller presents it will be accepted and allowed.
  ## These files may be re-read while poller is running.
  ## Example: ssl_cert_paths = ["/path/to/cert.pem", "/another/cert.pem"]
  ssl_cert_paths = []

# The following is optional and used for configurations with multiple UniFi controllers.

# You may repeat the following [[unifi.controller]] section as many times as needed to
# poll multiple controllers. Uncomment the entire section including [[unifi.controller]].
# Omitted variables will have their values taken from the defaults, above.
#
#[[unifi.controller]]
#  url         = "https://127.0.0.1:8443"
#  user        = "unifipoller"
#  pass        = "unifipoller"
#  sites       = ["all"]
#  save_sites  = true
#  hash_pii    = false
#  save_ids    = false
#  save_events = false
#  save_alarms = false
#  save_anomalies = false
#  save_dpi    = false
#  save_rogue  = false
#  verify_ssl  = false
#  ssl_cert_paths = []

**Comment by davidnewhall** [comment]
Same solution: rename your config.

**Comment by Videothek** [comment]
> Same solution: rename your config.

Actuelly i tried it and it doesnt work with the same output.

**Comment by Videothek** [comment]
Does the location of the config file matter?

**Comment by davidnewhall** [comment]
The location matters. It can be in one of two locations, both defined on this line of code: https://github.com/unpoller/poller/blob/master/build_unix.go#L6

The default/empty config exists in the container at `/etc/unifi-poller/up.conf`. You can either overwrite that one, or put it in `/config` at `/config/unifi-poller.conf`.

**Comment by Videothek** [comment]
> The location matters. It can be in one of two locations, both defined on this line of code: https://github.com/unpoller/poller/blob/master/build_unix.go#L6
> 
> The default/empty config exists in the container at `/etc/unifi-poller/up.conf`. You can either overwrite that one, or put it in `/config` at `/config/unifi-poller.conf`.

Hello,

thanks for the fast reply.

I tried to put the config file in `/etc/unifi-poller/up.conf` as well as `/etc/unifi-poller/unifi-poller.conf`

My command to run looked than like that: `sudo docker run -v /etc/unifi-poller/unifi-poller.conf:/config/unifi-poller.conf golift/unifi-poller`

Now i get more error messages like this: `cnfg unmarshal: unmarshaling file [/config/unifi-poller.conf]: Near line 39 (last key parsed 'poller.Password'): expected key separator '=', but got 'f' instead`

Any Ideas?

Thank You in Advance.

**Comment by davidnewhall** [comment]
That means the config file format is bad, or you're passing something that is not a poller config file. Can you share the file? Also, try this:
```
sudo docker run -v /etc/unifi-poller:/config golift/unifi-poller
```

**Comment by Videothek** [comment]
> That means the config file format is bad, or you're passing something that is not a poller config file. Can you share the file? Also, try this:
> 
> ```
> 
> sudo docker run -v /etc/unifi-poller:/config golift/unifi-poller
> 
> ```

Hmm weird,

this is my config file: [https://github.com/unpoller/unpoller/blob/master/examples/up.conf.example](https://github.com/unpoller/unpoller/blob/master/examples/up.conf.example)

I will try the other command later.

Thank You for your help.

**Comment by davidnewhall** [comment]
That's not your config file.

**Comment by Videothek** [comment]
> That's not your config file. 

This is the example config, i dont want to share my passwords.

Everything in this file is the same except the variables like IPs and Passwords.

**Comment by davidnewhall** [comment]
Good luck.

**Comment by Videothek** [comment]
> Good luck.

Well the command `sudo docker run -v /etc/unifi-poller:/config golift/unifi-poller ` doesnt work.

Why do you need my exact config file?

Everything is identical except the variables.

**Comment by davidnewhall** [comment]
I don't. I suspect the error message telling you line 30 is malformed should be enough for you to troubleshoot and fix the problem.

**Comment by Videothek** [comment]
> I don't. I suspect the error message telling you line 39 is malformed should be enough for you to troubleshoot and fix the problem.

I have tried to uncomment the line after that i get the next error on another line and so on.

So I dont think i cant fix it on my own.

I would if i think i could do anything but i ran out of ideas.

**Comment by davidnewhall** [comment]
Try using env variables instead of a config file.

**Comment by Videothek** [comment]
> Try using env variables instead of a config file.

Ok thx i will try it later.

**Comment by Videothek** [comment]
> Try using env variables instead of a config file.

Hello now i can test the variables.

Could you show me an example on how to write those variables?

Thx :-)

**Comment by davidnewhall** [comment]
```shell
docker run -e UP_UNIFI_DEFAULT_URL=http://localhost:8443 -e UP_UNIFI_DEFAULT_PASS=superSecret123 golift/unifi-poller
```

The two variables shown here are the bare minimum, but you probably need to also pass `UP_INFLUXDB_URL` if you're using InfluxDB. All variables are documented here: https://unpoller.com/docs/install/configuration

**Comment by Videothek** [comment]
> ```shell
> docker run -e UP_UNIFI_DEFAULT_URL=http://localhost:8443 -e UP_UNIFI_DEFAULT_PASS=superSecret123 golift/unifi-poller
> ```
> 
> The two variables shown here are the bare minimum, but you probably need to also pass `UP_INFLUXDB_URL` if you're using InfluxDB. All variables are documented here: https://unpoller.com/docs/install/configuration

Hello,

thanks but i tried with the config file a little bit more.

I got it to work now.

I shranked down my config file to this:

`[unifi.defaults]
  url  = "https://controller_url:8443"
  user = "read_only_user"
  pass = "read_only_user_password"
  save_dpi = true
[influxdb]
  url  = "http://influxdb_url:8086"
  db = "database_name"
  user = "influxdb_user"
  pass = "influxdb_password"`

And placed it in `/etc/unifi-poller/unifi-poller.conf`

Than I start the unpoller with: `sudo docker run -v /etc/unifi-poller:/config golift/unifi-poller`

Thank You for your help and sorry for wasting your time.

Hope it helps someone else too.

:-)

**Comment by 877dev** [comment]
> Rename it to `unifi-poller.conf`. The documentation is currently ahead of the app. It was hastily renamed.

That worked for me using Docker Compose as well, thanks!

**Comment by beezub99** [comment]
the documentation is littered with careless mistakes and gaps. 

look man, i get that this isn't your business but you are wasting peoples time. at least have a disclaimer that the documentation is just plain incorrect and you are likely to spend hours figuring it out. 

either that or care enough to spend an hour running through a fresh install for each path and correcting the documentation.

**Comment by davidnewhall** [comment]
@beezub99 Submit a PR with the disclaimer. Happy to include it.

**Comment by beezub99** [comment]
i deleted my comment because it was harsh. but i would be happy to take note of the documentation errors i found and send them over if that helps.

**Comment by davidnewhall** [comment]
I've had very little give a fucks about this project since Ubiquiti hit me with a cease and desist. One day I'll care enough to update the readme to that affect. PRs welcome.

**Comment by beezub99** [comment]
thats fair enough, i didn't realize they had done that. definately in line with how they operate. i apologies for the post, I think i was taking my frustration of them out on you.

**Comment by davidnewhall** [comment]
Sorry it's been frustrating. Not many people 'know'. I just slipped away. If you join discord I'm happy to provide assistance there.

**Comment by platinummonkey** [comment]
updated this in 2.4.x

https://github.com/unpoller/unpoller/blob/master/pkg/poller/config.go#L39

```
/etc/unpoller/up.conf
```

docs will get updated soon-ish
