### ISSUE TITLE
unable to install via repo

### ISSUE THREAD

**Issue by LunaticSerenade** [unpoller/unpoller#365]
Hello;

When I use this command:

curl -s https://golift.io/repo.sh | sudo bash -s - unpoller

It returns E: Unable to locate package unpoller. Given that's the instruction on your site, it may be worth looking at.

**Comment by davidnewhall** [comment]
`sudo apt install unifi-poller`

The app rename has not been finalized yet.

**Comment by OnkelDom** [comment]
Please leave a comment on https://unpoller.com/docs/install/cloudkey
i have the same issue.

**Comment by mschwieger** [comment]
The documentation on unpoller.com and https://github.com/unpoller/unpoller.github.io seem to be out of sync.
I had the same problem as @LunaticSerenade . I even started with Ubuntu 18.04 because that seemed to be the supported version. Only to find out, that 20.04 package repos were being installed.
Once I figured those problems out, everything went very smoothly.

So use 
```curl -s https://golift.io/repo.sh | sudo bash -s - unifi-poller```

and use Ubuntu 20.04, if you are on Linux and want to use Ubuntu.

**Comment by lslamp** [comment]
This package seems to have changed somewhat since I last installed it.

running the curl command does not work. I then tried the apt install and that worked fine.

but no service was created. Where can I get details of the installation process and what is expected
Lawrence

**Comment by davidnewhall** [comment]
It's still named `unifi-poller`.

**Comment by lslamp** [comment]
this can be closed

**Comment by platinummonkey** [comment]
this is updated, see https://packagecloud.io/golift/pkgs
