### ISSUE TITLE
Bandwidth Accuracy: Unpoller Vs Comcast

### ISSUE THREAD

**Issue by ThePieMonster** [unpoller/unpoller#389]
I am comparing total WAN usage using rx_bytes + tx_bytes (see the tagged GitHub Issue https://github.com/unpoller/unpoller/issues/293) over a 30 day time period with that of Comcast's data usage page. 

Currently for the first 5 days of the month, I see Comcast showing 77 GB of data used while Unpollers usage is at 108 GB. How can these values be so different? 

Using v2.1.3.

**Comment by davidnewhall** [comment]
To be clear, it's not unpoller's metrics. It's your controller's metrics, being visualized by Grafana. You should be able to make the same API calls to your controller at the beginning of the month and again later to compare what it's reporting.

**Comment by ThePieMonster** [comment]
Yes that's correct, to be more clear, I was unsure if you were aware of any potential issues with viewing the data that Unpoller pulls and/or could Unpoller be pulling to frequently and causing some data to be written twice causing a inflation of the overall data?

**Comment by davidnewhall** [comment]
The calculation of bandwidth over a period of time is not something I've put enough time into to figure out. Mostly because it's difficult, and seems to not work correctly, but it's been a long time since I dug into this problem. Poller just grabs the "total bytes transferred" and stores it in influx with a time stamp. How often that happens (frequency) doesn't change the raw data. All you need is the difference between two points from different times to calculate the data transferred. You can do this with raw `SELECT` commands in InfluxDB to double check what Grafana is showing you and to double check that poller is writing the correct numbers from your controller.

**Comment by ThePieMonster** [comment]
Thanks for the response. Here is the query that I came up with. Also Grafana shows the same output when you use a similar query as expected. 

**InfluxDB**

![image](https://user-images.githubusercontent.com/11359134/148478080-4a5cbeb0-13b9-4d3d-ab78-c64729fd7a6c.png)

![image](https://user-images.githubusercontent.com/11359134/148478059-82514e79-8d55-46c0-810b-df56a76a12dd.png)

**Xfinity**

![image](https://user-images.githubusercontent.com/11359134/148478785-3e968f2c-ee05-4bec-b12d-f537208893ef.png)


**UniFi**

UniFi just shows the total of all traffic across everything in the UI. So I can't narrow down just the WAN port. Basically, this image is useless. Hopefully a UI update from UniFi will add a feature for WAN monitoring. 

![image](https://user-images.githubusercontent.com/11359134/148479276-48b637ac-e56d-4875-b41a-afdbb2880091.png)

**Comment by platinummonkey** [comment]
I think this is answered, the UI is doing a sum across the timespan to accomplish this, and grafana, etc-all have some similar query mechanism to accomplish this
