### ISSUE TITLE
Polling Information Causes High CPU Usage on UDM

### ISSUE THREAD

**Issue by michaelpietzsch** [unpoller/unpoller#396]
Hi,

ive got the Poller fetching multiple UDMs.
All seem to run fine except one. I presume it is caused when using DPI or something of that nature
The poller is initially able to get some information but after a few seconds the cpu on the UDM spikes and the webinterface (API) becomes unrespnsive and times out.

Has anyone encounterd something similar?

**Comment by cdalvaro** [comment]
Same issue.

The load on the UDM increases during time until the system turns unresponsive.

I started to notice this behavior after adding an USW-24-PoE into my network. (Maybe it's a coincidence)

**Comment by davidnewhall** [comment]
Has anyone contacted Ubiquiti to find out why the product is doing this? Unpoller does it GET requests to a /api endpoints.

**Comment by giovannirco** [comment]
I was trying to get unpoller fetching my UDM-Pro and had this same issue, as soon as it got 2 or 3 batch of metrics it then crashed and I had to restart it. Since I am still doing some tests with my setup and moving things around I unintentionally noticed a CPU drop when I unplugged a Synology NAS with 4 port bonding to USW-Pro switch. it was always running at 60%-70% before and now hovers around 20%, not only because of the bonding but the NAS has some docker images running that may affet CPU usage IDK. The switch is connected over SFP to the UDM-pro so perhaps when more high throughput ports is connected the UDM-Pro uses more CPU to route the traffic? I wish to have the traffic being done by the switch, this is my next test after these findings and perhaps I will be able to fetch the UDM-Pro with unpoller without problem.
I also wonder if the unpoller has the same behaviour if installed as a docker image inside UDM-Pro, I might try this first and post my findings here

**Comment by cdalvaro** [comment]
After some trials, I realized I have enabled Jumbo frames for the whole network except for the UDM-Pro. When I enabled Jumbo frames on the UDM-Pro (through the legacy interface) the the load of the UDM-Pro was stable and running properly.

Jumbo frames can increase load on network devices if it is not properly configured on all of them.

**Comment by giovannirco** [comment]
>After some trials, I realized I had enabled Jumbo frames for the whole network except for the UDM-Pro. When I enabled Jumbo frames on the UDM-Pro (through the legacy interface) the the load of the UDM-Pro was stable and running properly.
>Jumbo frames can increase load on network devices if it is not properly configured on all of them.

Im wondering if this has fixed the unpoller for you, I have just checked and I didnt have Jumbo frames enabled everywhere, just made sure I got it enabled properly and I fired unpoller again and it crashed my UDM-Pro once again

**Comment by cdalvaro** [comment]
> > After some trials, I realized I had enabled Jumbo frames for the whole network except for the UDM-Pro. When I enabled Jumbo frames on the UDM-Pro (through the legacy interface) the the load of the UDM-Pro was stable and running properly.
> > Jumbo frames can increase load on network devices if it is not properly configured on all of them.
> 
> Im wondering if this has fixed the unpoller for you, I have just checked and I didnt have Jumbo frames enabled everywhere, just made sure I got it enabled properly and I fired unpoller again and it crashed my UDM-Pro once again

I'm sorry to hear that. The other change I made was to override the Link Speed of the SFP port to 1Gbps.

Since I'm not totally sure the issue is fixed for me, I've set some alerts to let me stop unpoller before the UDM-Pro crashes.

**Comment by davidnewhall** [comment]
Highly recommend opening a support request with Ubiquiti. Your router crashing is a high-severity bug imho; jumbo frames or not.

**Comment by bondskin** [comment]
running UDM with 1.12.15 and had 6 days running without any issues while unpoller was disabled.
I have now enabled it again and will monitor.
If it causes another outage on UDM, I'll report to UI.
No Jumbo Frames in use here.
Polling ist set to 1min.

**Comment by giovannirco** [comment]
https://github.com/unpoller/unpoller/issues/396#issuecomment-1101273032

> running UDM with 1.12.15 and had 6 days running without any issues while unpoller was disabled. I have now enabled it again and will monitor. If it causes another outage on UDM, I'll report to UI. No Jumbo Frames in use here. Polling ist set to 1min.

Have you had any other issues? I just tried this again today after reinstalling my udm-pro with a clean setup without unifi user, just local admin account, unpoller is again pushing the cpu to 100%

**Comment by platinummonkey** [comment]
is this still happening on 2.4.6+

**Comment by Proplex** [comment]
I just had to stop using unpoller because of this problem. v2.7.11 of unpoller, UDM Pro on 2.5.17. CPU would continually increase over ~12 hours until 100% utilization killing the UDMP. 
![IMG_0276](https://user-images.githubusercontent.com/2215601/228320696-ccf65733-ddd3-4e64-9126-f94943d4f757.jpeg)

**Comment by davidnewhall** [comment]
Has anyone opened a support request with Ubiquiti? API requests to the controller should not trigger the appliance to die; definitely something we need the manufacturer to look into.
