### ISSUE TITLE
Upgrading to 2.7.20 causes Influx write errors

### ISSUE THREAD

**Issue by manicmoose** [unpoller/unpoller#580]
Hi,

Running on Debian 12 (bookworm) - Unpoller installed via apt repo.

Was on 2.7.14 and upgraded to 2.7.20.
Started getting the following in 'syslog' every 30 seconds (poll interval):

`Jul 19 21:33:30 server unpoller[965454]: 2023/07/19 21:33:30 [ERROR] influxdb.Write(points): {"error":"partial write: field type conflict: input field \"rx_bytes-r\" on measurement \"subsystems\" is type integer, already exists as type float dropped=5"}`

Reverted back to 2.7.14 and the errors go away.

NB. Also seems that unpoller did not automatically restart after the upgrade or the downgrade, so had to do that manually.

**Comment by geiseri** [comment]
I found this too.  If I create a new database it seems to work again.

**Comment by platinummonkey** [comment]
Yes there was a data type change from the newer versions of the unifi APIs. I’ve been adding more type testing coverage to this tool to make this more obvious is changelogs

**Comment by manicmoose** [comment]
Uhhhh....sorry, but what is the resolution/fix, @platinummonkey?
Did you change some code to resolve the errors (didn't see anything in the receent commits), or is there something we need to do to resolve them ourselves?

**Comment by platinummonkey** [comment]
ah sorry, in another ticket. The sad answer is drop the influx table for those points affected 😵 since influx lacks the ability to migrate the data type. If you wanted to backfill the data you would likely need to do this yourself and query the history, store it, drop the data, turn on unpoller and it'll create the new table with the new type, backfill with the correct type. 😵 

This seems to be a strict limitation of influx. I'm not sure if their latest release of v3 has improved this or not for number types.
