### ISSUE TITLE
grafana/influxdb dashboards gets confused by multiple choice variables

### ISSUE THREAD

**Issue by aliher1911** [unpoller/unpoller#596]
I'm using UAP Insights and Client Insights dashboards with InfluxDB.
Out of the box they showed no data as it can't fetch variable values.

This is caused by `$Var` being expanded into list which is not a valid regex so nothing is matching. Replacing variable names with advanced syntax with format `${Var:regex}` fixed the problem for me.
For example site names for controller doesn't work correctly when using existing query:
```
show tag values from "uap" with key="site_name" where source =~ /^Controller$/
```
but works fine with
```
show tag values from "uap" with key="site_name" where source =~ /^${Controller:regex}$/
```
because regex format escapes () and / that could be present in the name.
I had to apply that to all variables using matching and now it works fine.

It would be helpful to update then on grafana website to simplify imports.

**Comment by BogdanX86** [comment]
Thanks to @aliher1911 I figured out that the Client Insights dashboard was broken for me because of these the Wireless and Wired variables.  New values as follows:

Wireless
``SHOW TAG VALUES FROM "clients" WITH KEY = "name" WHERE site_name =~ /^${Site:regex}$/ AND ap_name =~ /^{AP:regex}$/ AND is_wired=false``

Wired
``SHOW TAG VALUES FROM "clients" WITH KEY = "name" WHERE site_name =~ /^${Site:regex}$/ AND sw_name =~ /^{Switch:regex}$/ AND `is_wired=true`

**Comment by platinummonkey** [comment]
This should be fixed in recent changes to the dashboards
