### ISSUE TITLE
UXG/UDM dashboard not showing some data & would love to customize some filed names

### ISSUE THREAD

**Issue by SemoTech** [unpoller/unpoller#624]
Hey everyone, I setup unpoller recently and love all the data it pulls. My thanks to @davidnewhall and everyone else that has spent their precious time to make this happen. You all rock! 

I noticed in the UXG Dashboard (which I am using with a UDM-SE v3.1.16) that an entire section is showing "N/A" in green for Uplink, Desktop, Users, etc... (see screenshot attached).  Any Ideas how to get this data to populate?

Also, is there any way to customize the Ethernet Port names from current "eth8" and "eth10" to something more legible like "eth8 - ISP X" and "eth10 - ISP Y"?  Since I have 2 ISP's and I really need to easily differentiate who's WAN connection and data bandwidth I am using.

Lastly, any way to see Total Data Usage (per WAN connection) between specific dates? 

Thanks in advance.

![image](https://github.com/unpoller/unpoller/assets/1452100/9c18fb5f-46f9-495f-950b-76ddb4c62cde)

**Comment by SeekingHelp24** [comment]
Second this! I'm looking to see if there are any other issues about this that may have been closed already. I was told the issue is that Variable names were changed by Unifi. I am by no means a developer, just merely a user but I'm certainly looking to see if there have been any advancements made on this front!

**Comment by RedEchidnaUK** [comment]
For the metrics that are not showing. I was able to get them to work by editing the panel, and making sure under ‘Value options’, the field was set to ‘Numeric Fields’.

If you want to customise the names of fields then the easiest way is probably ‘field overrides’ which you can find in the Grafana documentation.

**Comment by matthiasschoger** [comment]
Encountered a similar issue with many graphs. Turns out that the __interval variable was to blame. After I replaced it in the query statement with __rate_interval, the graphs were looking fine again.

Pro tip: Get the JSON for the panel by going to settings->JSON, copy&paste the full JSON to a text editor, do a gobal search&replace there and paste everything back into the JSON view.
